@startuml C4 Components Module (zoom-in)
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

AddComponentTag("payment", $bgColor="#4ce065")
AddComponentTag("transaction", $bgColor="#e3b868")
AddComponentTag("cards", $bgColor="#FF69B4")
AddComponentTag("cqrs", $bgColor="#29118a", $fontColor="#ffffff")

System_Boundary(c1, "Modular Credit Card System") {
    Component(api, "API Host", ".NET Core API")
    
    Boundary(paymentModule, "Payment Module") {
        Component(paymentApi, "Payment.Api", ".NET Core API", $tags="payment")
    }

    Boundary(transactionModule, "Transaction Module") {
        Component(transactionApi, "Transaction.Api", ".NET Core API", $tags="transaction")
    }

    Boundary(cardsModule, "Cards Module") {
        Component(cardsApi, "Cards.Api", ".NET Core API", $tags="cards")
        Container(cardsIntegration, "Integration", "Implements Facade Pattern") {
            Component(iCardIntegrationApi, "ICardIntegrationApi", "Interface for Cards API", $tags="cards")
            Component(cardIntegrationApi, "CardIntegrationApi", "Facade Implementation", $tags="cards")
        }
        Component(cardsData, "Cards data", "Database schema", $tags="cards")
        Component(cqrsMediator, "CQRS", "Handles CQRS Commands/Queries", "(MediatR)", $tags="cqrs")
    }
}

Rel(api, paymentApi, "Delegates to")
Rel(api, transactionApi, "Delegates to")
Rel(api, cardsApi, "Delegates to")

Rel(cardsApi, cardsIntegration, "Uses")
Rel(cardsIntegration, iCardIntegrationApi, "Implements")
Rel(iCardIntegrationApi, cardIntegrationApi, "Implemented by")
Rel(cardIntegrationApi, cqrsMediator, "Uses MediatR for CQRS")

@enduml