export const CARD_SYMBOLS = {
    CARD_REPOSITORY: Symbol('CARD_REPOSITORY'),
    CARD_LIST: Symbol('CARD_LIST'),
    CARD_CREATE: Symbol('CARD_CREATE'),
    CARD_DELETE: Symbol('CARD_DELETE'),
    CARD_UPDATE: Symbol('CARD_UPDATE')
}